DROP TABLE IF EXISTS events,users,categories,compilations,compilation_event,requests,comments;

CREATE TABLE IF NOT EXISTS users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT pk_user PRIMARY KEY,
    name  varchar(255) NOT NULL  CONSTRAINT uq_user_email UNIQUE,
    email varchar(512)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT pk_categories PRIMARY KEY,
    name varchar(255) NOT NULL CONSTRAINT uq_categories_name UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT pk_compilations PRIMARY KEY,
    title  varchar(255),
    pinned boolean
);

CREATE TABLE IF NOT EXISTS events
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT pk_event PRIMARY KEY,
    title              varchar(255),
    annotation         varchar(2048),
    description        varchar(2048),
    created_on         timestamp WITHOUT TIME ZONE,
    event_date         timestamp WITHOUT TIME ZONE,
    category_id        bigint CONSTRAINT fk_category REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE,
    initiator_id       bigint CONSTRAINT fk_event REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    location_lon       double precision,
    location_lat       double precision,
    paid               boolean,
    participant_limit  bigint,
    published_on       timestamp WITHOUT TIME ZONE,
    request_moderation boolean,
    state              varchar(30)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT pk_request PRIMARY KEY,
    created_on   timestamp WITHOUT TIME ZONE,
    requester_id bigint NOT NULL  CONSTRAINT fk_request_user REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    event_id     bigint NOT NULL CONSTRAINT fk_request_event REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE,
    status       varchar(255)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT pk_column PRIMARY KEY,
    created_on   timestamp WITHOUT TIME ZONE,
    author_id bigint NOT NULL CONSTRAINT fk_comment_user REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    event_id     bigint NOT NULL CONSTRAINT fk_comment_event REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE,
    inform      varchar(2048)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_event
(
    compilation_id int NOT NULL,
    event_id       int NOT NULL CONSTRAINT fk_event_compilation
        REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE
);
