DROP TABLE IF EXISTS events,users,categories,compilations,compilation_event,requests,comments;

CREATE TABLE IF NOT EXISTS users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  varchar(255)                            NOT NULL,
    email varchar(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(255)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_name UNIQUE (name)

);

CREATE TABLE IF NOT EXISTS compilations
(
    id     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  varchar(255),
    pinned boolean,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS events
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              varchar(255),
    annotation         varchar(2048),
    description        varchar(2048),
    created_on         timestamp WITHOUT TIME ZONE,
    event_date         timestamp WITHOUT TIME ZONE,
    category_id        bigint,
    initiator_id       bigint,
    location_lon       double precision,
    location_lat       double precision,
    paid               boolean,
    participant_limit  bigint,
    published_on       timestamp WITHOUT TIME ZONE,
    request_moderation boolean,
    state              varchar(30),
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on   timestamp WITHOUT TIME ZONE,
    requester_id bigint                                  NOT NULL,
    event_id     bigint,
    status       varchar(255)                            NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on   timestamp WITHOUT TIME ZONE,
    author_id bigint                                  NOT NULL,
    event_id     bigint,
    inform      varchar(2048)                            NOT NULL,
    CONSTRAINT pk_column PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_event
(
    compilation_id int NOT NULL,
    event_id       int NOT NULL
);

ALTER TABLE events
    ADD CONSTRAINT fk_event FOREIGN KEY (initiator_id)
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE events
    ADD CONSTRAINT fk_category FOREIGN KEY (category_id)
        REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE requests
    ADD CONSTRAINT fk_request_user FOREIGN KEY (requester_id)
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE requests
    ADD CONSTRAINT fk_request_event FOREIGN KEY (event_id)
        REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE comments
    ADD CONSTRAINT fk_comment_user FOREIGN KEY (author_id)
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE comments
    ADD CONSTRAINT fk_comment_event FOREIGN KEY (event_id)
        REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE compilation_event
    ADD CONSTRAINT fk_event_compilation FOREIGN KEY (event_id)
        REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE;
