spring:
  sql:
    init:
      mode: always
  datasource:
    username: root
    url: jdbc:postgresql://localhost:6541/stats-db
    driverClassName: org.postgresql.Driver
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
server:
  port: '9090'