DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        varchar(50),
    uri        varchar(50),
    ip         varchar(50),
    time_stamp timestamp WITHOUT TIME ZONE
);

